project:
  type: website
  output-dir: docs #this will determine where your rendered pages (in this example, Project1 and 2) are stored. 
  
website:
  title: "Erico Yu's Home Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Teaching.qmd
    tools:
      - icon: github
        href: https://github.com/dongericoyu
      - icon: twitter
        href: https://x.com/DY_erico
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Erico Yu. All rights reserved."

format:
  html:
    theme: journal
    toc: true

editor: source

#remember to inlude the following lines to include all files in the `files/` folder that you want to link to.
resources: 
  - "files/**"
