project:
  type: website
  output-dir: docs

website:
  title: "Yongdong Chen's Website"
  navbar:
    right:
      - icon: github
        href: https://github.com/ydchenUmass
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Projects

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual